### ISSUE TITLE
vm.nr_hugepages

### ISSUE THREAD

**Issue by kakoni** [grayhemp/pgcookbook#5]
According to http://www.postgresql.org/docs/9.5/static/kernel-resources.html
hugepages is counted from VmPeak value 

> $ head -1 /path/to/data/directory/postmaster.pid
> 4170
> $ grep ^VmPeak /proc/4170/status
> VmPeak:  6490428 kB
> 6490428 / 2048 (PAGE_SIZE is 2MB in this case) are roughly 3169.154 huge pages, so you will need at least 3170 huge pages:

**Comment by grayhemp** [comment]
Right, that's what documentation says. However, IMHO, it can be arguable as well. I usually adjust hugepages number for the shared buffers amount, as it is, in the most cases, the only allocated chunk of memory where postgres can significantly benefit from them.

ps. The text is a little bit outdated, so, thanks for reminding me about updating it. I'll put more thoughts on hugepages in the new version.
